name: CI

on:
  push:
    branches: [ main ]          # rode sempre que houver commit no branch main
  pull_request:                 # opcional – roda em PRs também

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: |
          npm test -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT: reports/junit.xml        # caminho do relatório JUnit

      - name: Gerar relatório HTML do Cucumber (se aplicável)
        if: ${{ hashFiles('**/*.feature') != '' }}
        run: |
          node scripts/generateReport.js              # seu script gerador
          ls -R reports

      - name: Publicar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-testes                     # aparecerá na UI do GitHub
          path: reports/                              # pasta enviada

      - name: Resumo no Job
        run: |
          echo "### ✅ Pipeline concluída" >> $GITHUB_STEP_SUMMARY
          echo "*Commit:* ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "*Relatórios:* disponíveis em artefatos" >> $GITHUB_STEP_SUMMARY