name: Run Tests on Commit

on:
  push:
    branches:
      - main     # Defina a branch que você quer monitorar (geralmente 'main' ou 'master')
  pull_request:
    branches:
      - main     # Ações para pull request na branch 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Usando o Ubuntu mais recente como ambiente de execução

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'   # Usando a versão do Node.js que você precisa, aqui é a 14.x

    - name: Install Dependencies
      run: |
        npm install  # Instala as dependências do projeto

    - name: Run Tests with Cucumber and Playwright
      run: |
        npx cucumber-js  # Roda os testes com o Cucumber

    - name: Generate Allure Report
      run: |
        npm run generate-report  # Gera o relatório Allure

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report   # Faz o upload do relatório gerado para que você possa baixá-lo depois